# http://www.mikeball.info/blog/concourse-git-resource/
resources:

- name: my-repo
  type: git
  source:
    branch: master
    uri: git@github.com:my-org/my-repo.git
    private_key: {{private_github_private_key}}

jobs:

- name: git-log
  plan:
  - get: my-repo
  - task: show-log
      config:
        inputs:
        - name: my-repo
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: node
            tag: 6.3.1
        run:
          path: bash
          args:
            - -exc
            - cd my-repo
            - git --no-pager log
...
...
resources:

- name: my-repo
  type: git
  source:
    branch: master
    uri: git@github.com:my-org/my-repo.git
    private_key: {{private_github_private_key}}

jobs:

- name: commit-and-push-to-repo
  plan:
  - get: my-repo
  - task: commit-and-push
      config:
        inputs:
        - name: my-repo
        outputs:
        - name: my-repo-modified
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: node
            tag: 6.3.1
        run:
          path: bash
          args:
            - -exc
            - git clone my-repo my-repo-modified
            - cd akamai-gtm-archive-modified
            - echo $(date) > date_file.txt
            - git add .
            - git commit -m "add new date_file.txt date"
  - put: my-repo
    params:
      repository: my-repo-modified
