apiVersion: "cluster.k8s.io/v1alpha1"
kind: Cluster
metadata:
  name: test1-frbk5
  annotations:
    # The default service account used by master machines/vms created for this cluster
    gce.clusterapi.k8s.io/service-account-k8s-master: "master-test1-frbk5@denny-gcp-test.iam.gserviceaccount.com"
    # The default service account used by worker machines/cms created for this cluster
    gce.clusterapi.k8s.io/service-account-k8s-worker: "worker-test1-frbk5@denny-gcp-test.iam.gserviceaccount.com"
spec:
    clusterNetwork:
        services:
            cidrBlocks: ["10.96.0.0/12"]
        pods: 
            cidrBlocks: ["192.168.0.0/16"]
        serviceDomain: "cluster.local"
    providerSpec:
      value:
        apiVersion: "gceproviderconfig/v1alpha1"
        kind: "GCEClusterProviderSpec"
        project: "denny-gcp-test"
